# Generated by Django 5.1.6 on 2025-03-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_world_start_x_world_start_y_airplane"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverageStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_cells", models.IntegerField(default=0)),
                ("scanned_cells", models.IntegerField(default=0)),
                ("coverage_percentage", models.FloatField(default=0.0)),
                ("path_length", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "world",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_stats",
                        to="api.world",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PathPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pos_x", models.IntegerField()),
                ("pos_y", models.IntegerField()),
                (
                    "rotation",
                    models.CharField(
                        choices=[
                            ("UP", "UP"),
                            ("DOWN", "DOWN"),
                            ("LEFT", "LEFT"),
                            ("RIGHT", "RIGHT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "airplane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_points",
                        to="api.airplane",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["airplane", "timestamp"],
                        name="api_pathpoi_airplan_ca71a3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScannedCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pos_x", models.IntegerField()),
                ("pos_y", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "airplane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scanned_cells",
                        to="api.airplane",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scanned_cells",
                        to="api.world",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["world", "airplane"],
                        name="api_scanned_world_i_82211f_idx",
                    )
                ],
                "unique_together": {("world", "pos_x", "pos_y")},
            },
        ),
    ]
