# Generated by Django 5.1.6 on 2025-04-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_coveragestatistics_pathpoint_scannedcell"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="color",
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
    ]
