# Generated by Django 5.1.6 on 2025-04-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_airplane_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="flight_ended",
            field=models.BooleanField(default=False),
        ),
    ]
